services:

  nginx:
    image: nginx:1.21.3
    volumes:
      - ../:/app:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpfpm
      - db
    ports:
      - 8080:80

  phpfpm:
    user: '1000:1000'
    build: ./php/.
    volumes:
      - ../:/app:delegated

  db:
    image: mariadb:10.6
    ports:
      - 33061:3306
    volumes:
      - ./data:/bitnami/mysql/data:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=isto

  adminer:
    image: adminer
    depends_on:
      - nginx
    ports:
      - 8081:8080
